### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by agrecascino** [gitgood/Living-in-the-fast-Lain#1]
What are general music choices going to be? I could recommend some music. Also what formats for music?(modules pls)

**Comment by gitgood** [comment]
Music isn't a super high priority at the moment, though I'm leaning towards just generic Visual Novel piano melodies. Any suggestions?

**Comment by agrecascino** [comment]
mystique(parts 1,2,3) by Timelord and out of silence v2 by Jogeir Liljedahl.

**Comment by gitgood** [comment]
Great suggestions! I like the mystique songs, from Uplink right? I like the other one too, nice and retro. Just bookmarked both there. You could always try adding them in and see how it goes?

**Comment by agrecascino** [comment]
Yeah, the mystique songs are from uplink. A ton of Jogeir Liljedahl's is like that and I think a lot of his stuff would work quite well.

**Comment by gitgood** [comment]
I'll definitely look in to it!
